version: '3.7'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: position_app
        restart: unless-stopped
        tty: true
        command: php artisan serve --host=0.0.0.0
        ports:
            - "8008:8000"
        volumes:
            -   .:/var/www
        working_dir: /var/www
        networks:
            - app-network
    db:
        image: mysql:5.7.22
        container_name: position_db
        restart: unless-stopped
        tty: true
        ports:
            - "3308:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: dbRoot!23
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network
    mailhog:
            container_name: position_mailhog
            image: mailhog/mailhog
            ports:
                - "1026:1025"
                - "8026:8025"
            networks:
                - app-network
networks:
    app-network:
        driver: bridge
