version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: appposition
        restart: unless-stopped
        environment:
            SERVICE_NAME: app
        working_dir: /var/www/html
        ports:
            - "8008:8000"
        volumes:
            - ./:/var/www/html
    #Nginx Service
    nginx:
        container_name: appposition_nginx
        image: nginx:1.25.1
        ports:
            - "88:80"
            - "445:443"
        volumes:
            - ./nginx.conf/nginx.conf.conf:/etc/nginx.conf/nginx.conf/default.conf
        depends_on:
            - app

